import { Navbar } from "@/components/ui/navbar";
import { Toaster } from "@/components/ui/toaster";
import { useToast } from "@/components/ui/use-toast";
import { api } from "@/utils/api";
import { type GetServerSideProps } from "next";
import { useEffect, useMemo, useState } from "react";
import Head from "next/head";
import { CardBoard } from "@/components/ui/cardBoard";
import { Button } from "@/components/ui/button";
import { useFibboStore } from "@/stores/useFibboStore";
import { Coins, RotateCcw } from "lucide-react";

interface PropTypes {
  id: string;
}

export default function Planning({ id }: PropTypes) {
  const [meId, setMeId] = useState<string | null>("");

  const fibboStore = useFibboStore((state) => state);

  const { toast } = useToast();

  const ctx = api.useContext();

  const searchRoom = api.room.searchRoom.useQuery({ id });

  useEffect(() => {
    setMeId(localStorage.getItem("@me"));
    if(searchRoom.error) {
      console.log('condicao')
    }
  }, []);

  const getUser = api.user.searchUser.useQuery({ id: meId! });

  const removeUserRoom = api.room.removeUserRoom.useMutation({
    onSuccess: () => ctx.invalidate(),
    onError: (error) =>
      toast({
        title: "Something bad happened",
        description: error.message,
      }),
  });
  const updateFibbo = api.room.changeFibboUserRoom.useMutation({
    onSuccess: () => ctx.invalidate(),
    onError: (error) =>
      toast({
        title: "Something bad happened",
        description: error.message,
      }),
  });

  const resetFibbo = api.room.resetFibboRoom.useMutation({
    onSuccess: () => ctx.invalidate(),
    onError: (error) =>
      toast({
        title: "Something bad happened",
        description: error.message,
      }),
  });
  const revealFibbo = api.room.revealFibboRoom.useMutation({
    onSuccess: () => ctx.invalidate(),
    onError: (error) =>
      toast({
        title: "Something bad happened",
        description: error.message,
      }),
  });

  function removeUser(userToRemoveId: string) {
    removeUserRoom.mutate({ roomId: id, userToRemoveId, userAdminId: meId! });
  }

  function updateFibbonnacci(fibbo: string) {
    updateFibbo.mutate({
      fibbo,
      roomId: id,
      userId: meId!,
    });
  }

  function resetFibbonnacci() {
    resetFibbo.mutate({ roomId: id });
    fibboStore.resetFibbo();
    fibboStore.revealFibbo(false);
  }

  function revealFibbonacci() {
    revealFibbo.mutate({ roomId: id });
    fibboStore.revealFibbo();
  }

  const findMe = useMemo(() => {
    return searchRoom.data?.users.find((user) => user.id === meId);
  }, [searchRoom.data]);

  // useEffect(() => {
  //   if(typeof window !== 'undefined') {
  //     const findUser = searchRoom.data?.users.find((user) => user.id === meId);
  //   console.log(findUser)
  //   if (!findUser) {
  //     void router.push(`${id}/join`);
  //   }
  //   }
  // }, [searchRoom.data]);

  return (
    <>
      <Head>
        <title>Dev Planning - {searchRoom.data?.name}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen w-full">
        <Toaster />
        <Navbar
          isAdmin={getUser.data?.role === "admin"}
          removeUser={removeUser}
          list={searchRoom.data?.users}
        />
        <div className="relative flex min-h-screen w-full items-center justify-center">
          <div className="rounded-md bg-main p-10">
            <h1 className="text-4xl font-bold">Let's Planning!</h1>
            <p className="text-xl font-semibold">Select a card</p>
            {revealFibbo.data && (
              <>
                <h1 className="text-xl font-bold text-light/60">
                  Average:{" "}
                  <span className="text-light underline">
                    {revealFibbo.data.average}
                  </span>
                </h1>
                <h1 className="text-xl font-bold text-light/60">
                  Fibbonacci:{" "}
                  <span className="text-light underline">
                    {revealFibbo.data.fibbonacci}
                  </span>
                </h1>
              </>
            )}
            <div className="mt-2 flex min-w-52 gap-2">
              {getUser.data?.role === "admin" && !fibboStore.isFibboReveal ? (
                <Button variant="white" size="full" onClick={revealFibbonacci}>
                  <Coins /> Reveal
                </Button>
              ) : (
                getUser.data?.role === "admin" && (
                  <Button
                    variant="white"
                    size="full"
                    onClick={resetFibbonnacci}
                  >
                    <RotateCcw /> Reset
                  </Button>
                )
              )}
            </div>
          </div>
          {findMe && <CardBoard updateFibbonnacci={updateFibbonnacci} />}
        </div>
      </main>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const { id } = ctx.query;

  if (!id) {
    return {
      redirect: {
        destination: "/",
      },
      props: {},
    };
  }

  // const trpc = appRouter.createCaller({ db });
  // const result = await trpc.room.searchRoom({ id: id?.toString() });

  // if (!result) {
  //   return {
  //     redirect: {
  //       destination: "/",
  //     },
  //     props: {},
  //   };
  // }

  // const userParsed = result.users.map((user) => {
  //   user.createdAt = user.createdAt.toString() as unknown as string;
  // });

  return {
    props: {
      id: id.toString(),
    },
  };
};
